#!/bin/bash
# Discord Bot 快速修复指南

echo "🔧 Discord Bot 修复指南"
echo "======================"
echo ""
echo "问题诊断："
echo "- Discord Gateway 连接立即断开"
echo "- 通常是因为 MESSAGE CONTENT INTENT 未启用"
echo ""
echo "📋 修复步骤："
echo ""
echo "1. 打开 Discord Developer Portal："
echo "   https://discord.com/developers/applications"
echo ""
echo "2. 选择您的应用 → Bot → Privileged Gateway Intents"
echo ""
echo "3. ✅ 启用 'MESSAGE CONTENT INTENT'"
echo ""
echo "4. 点击 'Save Changes'"
echo ""
echo "5. 重启 Gateway："
echo ""
echo "   # 先停止当前进程"
echo "   pkill -f 'gearclaw.*gateway'"
echo ""
echo "   # 重新启动"
echo "   RUST_LOG=debug cargo run --package gearclaw_cli --bin gearclaw_cli -- gateway"
echo ""
echo "⚠️  重要提示："
echo ""
echo "MESSAGE CONTENT INTENT 是必须启用的权限！"
echo "没有这个权限，Bot 无法读取消息内容，会导致："
echo "  - Gateway 连接立即断开"
echo "  - Bot 无法接收任何消息"
echo "  - 看起来像是没有响应"
echo ""
echo "✅ 验证方法："
echo ""
echo "启用后，您应该看到这些日志："
echo "  ✅ 'Discord Gateway shard created, connecting...'"
echo "  ✅ 'Discord Gateway connected'"
echo "  ✅ 'Received Discord message from ...'"
echo ""
echo "❌ 如果仍然失败，检查："
echo ""
echo "1. Bot Token 是否正确："
echo "   echo \$DISCORD_BOT_TOKEN | cut -c1-10"
echo ""
echo "2. Bot 是否已添加到服务器"
echo ""
echo "3. Bot 是否有发送消息权限"
echo ""
